VERSION_NUMBER=${1:-'0.3.0'}

docker run -p 9091:8080 \
    -e INTERNAL_PORT=8080 \
    -e ATTIRE_TRACKER_DB_USERNAME \
    -e ATTIRE_TRACKER_DB_PASSWORD \
    -e ATTIRE_TRACKER_DB_DATABASE \
    -e ATTIRE_TRACKER_DB_HOST \
    -e ATTIRE_TRACKER_DB_PORT \
    attire-tracker:$VERSION_NUMBER 
